services:
  claude:
    image: kyxap/claude-sandbox
    pull_policy: build
    build:
      context: .devcontainer
      args:
        NODE_VERSION:
        CLAUDE_CODE_VERSION:
        GIT_DELTA_VERSION:
        KUBECTL_VERSION:
        WIZCLI_VERSION:
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYSLOG
      - SYS_NICE
    environment:
      FIREWALL: ${FIREWALL:-true}
      FIREWALL_VERBOSE: ${FIREWALL_VERBOSE:-false}
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.claude:/home/node/.claude
      - ~/.claude.json:/home/node/.claude.json
      - ~/.ssh/id_rsa:/home/node/.ssh/id_rsa:ro
      - .:/workspace
